const productionConstants = {
  BACKEND_ADDRESS: process.env.REACT_APP_BACKEND_ADDRESS,
  FRONTEND_ADDRESS: process.env.REACT_APP_FRONTEND_ADDRESS,
}

const developmentConstants = {
  BACKEND_ADDRESS: 'http://localhost:3000',
  FRONTEND_ADDRESS: 'http://localhost:3001',
}

const socketConstants = {
  CONNECT: 'connection',
  UPDATED_PARTY: 'updatedParty',
  UPDATED_PARTY_DATA: 'updatedPartyData',
  DISCONNECT: 'disconnect',
}

export default process.env.NODE_ENV === 'development'
  ? { ...developmentConstants, ...socketConstants }
  : { ...productionConstants, ...socketConstants }

export const DEFAULT_SNACKBAR_PROPS = {
  anchorOrigin: {
    vertical: 'bottom',
    horizontal: 'right',
  },
  autoHideDuration: 5000,
}

export const MESSAGES = {
  INVALID_PLAYLIST_SETTINGS: `
    Invalid input. Please ensure the following:
    - Title and duration are non-empty
    - Max duration is greater than 0 mins
    - All genres are valid
    `,
  FOLLOWED_PLAYLIST: 'Followed playlist',
  UNFOLLOWED_PLAYLIST: 'Unfollowed playlist',
  UPDATED_PLAYLIST: 'Playlist updated',
  LINK_COPIED: 'Party URL copied to clipboard',
  INVALID_PLAYLIST_JOIN: 'Invalid party URL. Please try again',
}

export const GENRES = [
  'acoustic',
  'afrobeat',
  'alt-rock',
  'alternative',
  'ambient',
  'anime',
  'black-metal',
  'bluegrass',
  'blues',
  'bossanova',
  'brazil',
  'breakbeat',
  'british',
  'cantopop',
  'chicago-house',
  'children',
  'chill',
  'classical',
  'club',
  'comedy',
  'country',
  'dance',
  'dancehall',
  'death-metal',
  'deep-house',
  'detroit-techno',
  'disco',
  'disney',
  'drum-and-bass',
  'dub',
  'dubstep',
  'edm',
  'electro',
  'electronic',
  'emo',
  'folk',
  'forro',
  'french',
  'funk',
  'garage',
  'german',
  'gospel',
  'goth',
  'grindcore',
  'groove',
  'grunge',
  'guitar',
  'happy',
  'hard-rock',
  'hardcore',
  'hardstyle',
  'heavy-metal',
  'hip-hop',
  'holidays',
  'honky-tonk',
  'house',
  'idm',
  'indian',
  'indie',
  'indie-pop',
  'industrial',
  'iranian',
  'j-dance',
  'j-idol',
  'j-pop',
  'j-rock',
  'jazz',
  'k-pop',
  'kids',
  'latin',
  'latino',
  'malay',
  'mandopop',
  'metal',
  'metal-misc',
  'metalcore',
  'minimal-techno',
  'movies',
  'mpb',
  'new-age',
  'new-release',
  'opera',
  'pagode',
  'party',
  'philippines-opm',
  'piano',
  'pop',
  'pop-film',
  'post-dubstep',
  'power-pop',
  'progressive-house',
  'psych-rock',
  'punk',
  'punk-rock',
  'r-n-b',
  'rainy-day',
  'reggae',
  'reggaeton',
  'road-trip',
  'rock',
  'rock-n-roll',
  'rockabilly',
  'romance',
  'sad',
  'salsa',
  'samba',
  'sertanejo',
  'show-tunes',
  'singer-songwriter',
  'ska',
  'sleep',
  'songwriter',
  'soul',
  'soundtracks',
  'spanish',
  'study',
  'summer',
  'swedish',
  'synth-pop',
  'tango',
  'techno',
  'trance',
  'trip-hop',
  'turkish',
  'work-out',
  'world-music',
]
