version: "3"

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    ports:
      - 3000:3000
    env_file:
      - ./api/.env
    volumes:
      - ./api:/api
    networks:
      - autodj
    depends_on:
      - db

  application:
    build:
      context: ./application
      dockerfile: Dockerfile
    container_name: application
    ports:
      - 3001:3001
    environment:
      - NODE_ENV=development
      - PORT=3001
    volumes:
      - ./application:/application
      - /application/node_modules
    networks:
      - autodj
    depends_on:
      - api

  db:
    image: mongo
    container_name: db
    command: mongod --quiet
    volumes:
      - mongo-data:/data/db
    ports:
      - 27017:27017
    networks:
      - autodj

networks:
  autodj:
    driver: bridge

volumes:
  mongo-data:
